### ISSUE TITLE
Option to disable mouse focus

### ISSUE THREAD

**Issue by manipuladordedados** [Drostina/EasyAwesomeWM#2]
Prevent window focus change moving the mouse.

**Comment by Drostina** [comment]
I will take a look at this today

**Comment by Drostina** [comment]
This has now been implemented, you will find the relevant setting in the settings.lua file (e.g where the theme selection is)
You will not need to download the entire pack and set it up again, only replace your rc.lua and settings.lua from the repo :)

I will leave this open for a couple more days in case anyone comes across some issues with this new feature

**Comment by manipuladordedados** [comment]
Thanks =)
